### PR TITLE
Clarify PEM cert chain order.

### PR DESCRIPTION
**Pull request by deadlysyn**
Added note box to help clarify proper order for pem cert chains.  Feel free to reformat, remove external link, etc -- main goal is saving future readers time remembering/looking up proper cert chain order.  :-)

Co-authored-by: Arron Hocking <ahocking@pivotal.io>
Co-authored-by: Rahul Jain <rahul@pivotal.io>
Co-authored-by: Shwan Neil <sneal@pivotal.io>

### CODE REVIEW

**Comment by deadlysyn** [comment]
PS: Thanks for merging!

**Comment by mlimonczenko** [comment]
Thank _you_, @deadlysyn!

**Comment by mlimonczenko** [comment]
@deadlysyn Do you intend for this to be on other major versions? Master corresponds to the v2.5 release.

**Comment by deadlysyn** [comment]
I think it could apply to any version, since it is generic advice.  Would you like me to PR additional branches?

**Pull request merged**
