### PR TITLE
Updated AWS signature references.

### PR DESCRIPTION
**Pull request by mxplusb**
Updated the AWS references in the installation guide to reflect AWS' official recommendations regarding signature version, with notes and links to the AWS S3 Signature Version documentation for user reference.

Signed-off-by: Mike Lloyd <mlloyd@pivotal.io>

### CODE REVIEW

**Comment by mxplusb** [comment]
@pivotal-cf/field-engineering please feel free to participate and provide feedback for this installation doc change.

**Comment by seviet** [comment]
Confirmed with @mxplusb that we should keep in the link. Mergin'!

**Comment by mxplusb** [comment]
Can we merge this into 1.6-current?

**Comment by seviet** [comment]
Yes! Will do. And also, 1.7, 1.8 & 1.9.

**Pull request merged**
