### PR TITLE
Corrects ALB name created by ARM template and provides azure cli comm…

### PR DESCRIPTION
**Pull request by doddatpivotal**
…and to get load balancer name

### CODE REVIEW

**Comment by seviet** [comment]
hey @doddatpivotal -- thanks for this PR! however, I'm wondering if the right thing to might be to update the ARM template at some point to use PAS? @mxplusb do you know what the state of support for the ARM template is?

**Comment by doddatpivotal** [comment]
hi @seviet -- your suggestion seems reasonable too.  It looks like the arm template was last updated in October of last year.

**Comment by mxplusb** [comment]
I am the primary maintainer of the PCF ARM template, but I don't actively maintain it at the moment, as well as it's surrounding documentation. It is fairly out of date and it needs to be updated to reflect the current state of the pivotal-cf/terraforming-azure output. There will also have to be an extensive run through of the documentation to make sure any changes are reflected there. Ideally, I'd like to get to it, but this is a time constraint issue, mostly.

For the moment, if updating the documentation to reflect a better experience when using the ARM template will help make it easier for folks that wish to use it, I don't see why not.

As far as backporting, 2.x is fine.

**Comment by seviet** [comment]
sounds good, @mxplusb -- let us know if you want to x-team pair on updating the docs whenever you have time to do so!

**Comment by doddatpivotal** [comment]
@mxplusb @seviet I used the ARM template because the following doc page says it is recommended over manual or terraform.  Is terraform actually the recommended procedure?  If so, should we update this page: https://docs.pivotal.io/pivotalcf/2-1/customizing/azure.html#install

**Comment by seviet** [comment]
you're right-- i believe Terraform is the way to go! I'll update it (@mxplusb let us know if you think differently)

**Comment by mxplusb** [comment]
Nah, terraform is the right way to go. We don't actively maintain GCP/AWS templates (to my knowledge), so the ARM template it a one-off.

**Pull request merged**
