### PR TITLE
Update azure-arm-template.html.md.erb

### PR DESCRIPTION
**Pull request by mxplusb**
Updating to reflect new ARM template.

### CODE REVIEW

**Comment by mxplusb** [comment]
This change should update the notes regarding the ARM template, and remove the comment about the extra storage accounts.

**Comment by mxplusb** [comment]
Fixes pivotal-cf/pcf-azure-arm-templates#8

**Comment by animatedmax** [comment]
Thank you, @mxplusb

**Comment by mxplusb** [comment]
@animatedmax can you share the staging docs link? I want to look at it to make sure it looks okay.

**Pull request merged**
