### PR TITLE
Describe using the Ops Manager API for installation_settings import/export

### PR DESCRIPTION
**Pull request by gcapizzi**
Reworded version of https://github.com/pivotal-cf/docs-pcf-install/pull/327 using the Ops Manager API and `curl` instead of `om`.

### CODE REVIEW

**Comment by pspinrad** [comment]
Thanks @gcapizzi -- does this apply to all versions of the Ops Man API since v1.12?

**Comment by ChunyiLyu** [comment]
@pspinrad Yes! Should we submit other PRs for other versions, or will the docs team be able to back port these changes for other PCF versions?

Thanks,
Chunyi && @MirahImage

**Comment by pspinrad** [comment]
We can back-port if you let us know-- so either way is great, either 1) PR to different branches, or 2) let us know in the single PR which other branches to cherry-pick to.  Thanks!

**Comment by pspinrad** [comment]
^^ for this one, I'll go ahead and cherry-pick.  Thanks again.

**Pull request merged**
