### PR TITLE
Fixes and small improvements to BBR docs for PCF 2.1

### PR DESCRIPTION
**Pull request by alamages**
We recently did a full manual backup and restore of PCF 2.1 as part of https://www.pivotaltracker.com/story/show/156377151. Here are a number of fixes and small improvements to the backup and restore docs.

cc @jamesjoshuahill

### CODE REVIEW

**Comment by alamages** [comment]
@kdolor-pivotal should we fix the conflicts or anyone else is looking at this?

**Comment by kdolor-pivotal** [comment]
Hi, @alamages. Thanks for your PR. Given the extensiveness of this PR, I just want to check with the PM to make sure these changes can be integrated.

**Comment by jamesjoshuahill** [comment]
Hi @kdolor-pivotal we would be happy to pair with you to go through these changes and our reasoning. We would like these fixes and improvements to go into master as well, so they are included in the PCF 2.2+ docs as well.

**Comment by kdolor-pivotal** [comment]
I paired with @alamages this morning to go over these changes. Merging. Thanks all.

**Pull request merged**
