### PR TITLE
Swicth OM instance type from m3 to m5 for AWS

### PR DESCRIPTION
**Pull request by matthewfischer**
The m3 type no longer exists, move references to the newest general
purpose type of m5.

### CODE REVIEW

**Comment by pspinrad** [comment]
@matthewfischer thanks so much for all the docs reviewing and correcting-- much appreciated!  For the image, can you just screencap the `m5` option selected, with a line or two above and below for context, and don't worry about including the `Family | Type |...` column headers?

Re the pcf.json file-- I'll check if it's used anywhere, may just be vestigial and delete-able.  Thanks again!!

**Comment by matthewfischer** [comment]
I believe that's what i did with the image - let me know if you need a change

**Comment by matthewfischer** [comment]
This bug (having m3.large) ended up trickling down into other software and caused issues in automation - if there are no issues, can we merge it?

**Comment by pspinrad** [comment]
Thanks @matthewfischer !

**Pull request merged**
